presencia/config/routes.rb
Rails.application.routes.draw do

  resources :emails
  resources :logs
  devise_for :users, path_prefix: 'devise'
  resources :cards
  resources :equipos
  resources :usuarios
  resources :users, only: [:show]

   root 'main#inicio'

   post '/gestion' => 'main#gestion'

   get '/gestion' => 'main#gestion'   

   post '/informacion' => 'main#informacion'

   get '/informacion' => 'main#informacion'

   get '/users' => 'users#index'
   post '/users' => 'users#create'

   get '/users/:id' => 'users#show'

   get '/users/:id/edit' => 'users#edit'

   patch 'users/:id' => 'users#update'

   get '/sign_up' => 'users#new'

   delete '/users/:id' => 'users#destroy'

   get '/buscar' => 'logs#buscar'
   get '/ver_info' => 'logs#ver_info'

end

presencia/app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :usuario
  has_many :logs
  
  validates :codigo, :activa, presence: {message: ": Campo obligatorio"}
  validates :codigo, length: {is: 4, message: ": Debe tener 4 dígitos"}
  validates :codigo, format: {with: /[0-9A-F]{4}/, message: ": Formato incorrecto"}
end

presencia/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.order(:usuario_id)
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit       
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        if !@card.usuario_id.blank?          
          u = Usuario.find(@card.usuario_id)          
          if u.card_id.nil?
            u.card_id = @card.id
            u.save
          else
            c = Card.find(u.card_id)
            c.activa = 0
            c.save
            u.card_id = @card.id
            u.save
          end
        end 

        format.html { redirect_to @card, notice: 'La tarjeta se ha creado correctamente.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
         if !@card.usuario_id.blank?          
          u = Usuario.find(@card.usuario_id)          
          if u.card_id.nil?
            u.card_id = @card.id
            u.save
          else
            c = Card.find(u.card_id)
            c.activa = 0
            c.save
            u.card_id = @card.id
            u.save
          end
        end         
        format.html { redirect_to @card, notice: 'La tarjeta se ha actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    if @card.usuario_id.blank?
      @card.destroy
      respond_to do |format|
        format.html { redirect_to cards_url, notice: 'La tarjeta se ha eliminado correctamente.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to cards_url, notice: 'No se puede eliminar una tarjeta asociada a un usuario.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:id, :codigo, :usuario_id, :activa)
    end
end

presencia/app/views/cards/index.html.erb
<div class="text-center">

<p id="notice"><%= notice %></p>

<h2 style="margin-bottom: 30px;"><b>Gestionar Tarjetas<b></h2>
<div class="table-responsive" style="margin-left: 15px; margin-right: 15px;">
  <table class="table table-condensed table-hover">
    <thead>
      <tr>
        <th class="encabezado success">Codigo</th>
        <th class="encabezado info">Usuario</th>
        <th class="encabezado success">Activa</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @cards.each do |card| %>
        <tr>
          <td class='cuerpo'><%= card.codigo %></td>
          <td class="cuerpo"><%=
            if !card.usuario.nil? 
              card.usuario.nombre + ' ' + card.usuario.apellidos 
            end
          %></td>
          <td class="cuerpo">
            <% if card.activa == 1 %>
            <%= r = "SÍ" %>
            <% else %>
            <%= r = "NO" %>
            <% end %>
          </td>
          <td style="border-bottom: 1px solid #CCCCCC;">
            <%= link_to 'Ver', card , class: 'btn btn-default btn-sm' %>
            <%= link_to 'Editar', edit_card_path(card) , class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Borrar', card, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'Nueva Tarjeta', new_card_path , class: 'btn btn-default'%>
<%= link_to 'Volver', {controller: "main", action: "gestion"}, {class: "btn btn-danger"} %>
</div>

presencia/app/views/cards/show.html.erb
<div class="text-center">

<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @card.codigo %>
</p>

<p>
  <strong>Usuario:</strong>
  <%=
  if !@card.usuario.nil? 
    @card.usuario.nombre + ' ' + @card.usuario.apellidos 
  end 
  %>
</p>

<p>
  <strong>Activa:</strong>
  <% if @card.activa == 1 %>
  <%= r = "SÍ" %>
  <% else %>
  <%= r = "NO" %>
  <% end %>
</p>

<%= link_to 'Editar', edit_card_path(@card) , class: 'btn btn-primary' %> 
<%= link_to 'Volver', cards_path , class: 'btn btn-danger' %>

</div>

presencia/app/views/logs/ver_info.html.erb
<div class="text-center">

<h2 style="margin-bottom: 25px;"><b>Registros para el usuario<br><%= @usuario.nombre+" "+@usuario.apellidos %></b></h2>

<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3"></div>

<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">

<div class="table-responsive">
	<table class="table table-condensed table-hover">
		<thead>
			<tr>
				<th class="encabezado success">Hora Registro</th>
				<th class="encabezado info">Lectora</th>
				<th class="encabezado success">Tarjeta</th>
				<th class="encabezado info">Entrada/Salida</th>
			</tr>
		</thead>
		<tbody>
			<% @registros.each do |r| %>
				<tr>
					<td class="cuerpo"><%= r.tiempo_registro.strftime("%F %T") %></td>
					<td class="cuerpo"><%= r.equipo.ip %></td>
					<td class="cuerpo"><%= r.card.codigo %></td>
					<td class="cuerpo">
					<%= 
					if r.entrada 
						res = 'ENTRADA'
					else
						res = 'SALIDA'
					end
					%>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

<% @registros.each do |r|
	if r.entrada
		@aux = r.tiempo_registro.to_time.to_i
	else
		if @aux != 0
			h = r.tiempo_registro.to_time.to_i - @aux
			res = h/3600.0
			#@horas.push([res.round(2),r.tiempo_registro.strftime("%F")])
			if @horas.length != 0
				fecha = r.tiempo_registro.strftime("%F")
				@nuevo = true
				@horas.each do |h|
					if(h.second.eql? fecha)
						h[0] += res.round(2)
						@nuevo = false
					end
				end
				if(@nuevo)
					@horas.push([res.round(2),r.tiempo_registro.strftime("%F")])
				end
			else
				@horas.push([res.round(2),r.tiempo_registro.strftime("%F")])
			end
			@acum += res
		end
	end
end 
if(@horas.length != 0)
	@media = @acum / @horas.length
end
%>

<<<<<<< HEAD
<h4><b>Total Horas Semanales</b></h4>
=======
<h4><b>Total Horas En El Periodo </b></h4>
>>>>>>> 69322e6b785d76193e97a1d8de90e28ec133ed83
<%= r = @acum.round(2).divmod 1 
	hora = r.first
	min = ((r.second*100) * 60)/100
	res = hora.to_s+":"+min.to_i.to_s %><br>
<br>
<h4><b>Media Horas Diarias</b></h4>
<%= r = @media.round(2).divmod 1 
	hora = r.first
	min = ((r.second*100) * 60)/100
	res = hora.to_s+":"+min.to_i.to_s %><br>
<br>
<h4><b>Horas Por Día</b></h4>
<div class="table-responsive">
<table class="table table-condensed table-hover">
	<thead>
		<tr>
			<th class="encabezado success">Fecha</th>
			<th class="encabezado info">Horas</th>
		</tr>
	</thead>
	<tbody>
		<% @horas.each do |h| %>
		<tr>
			<td class="cuerpo"><%= h.second %></td>
			<td class="cuerpo"><%=r = h.first.round(2).divmod 1
				hora = r.first
				min = ((r.second*100) * 60)/100
				res = hora.to_s+":"+min.to_i.to_s %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>



<br><%= link_to ' Volver ', '/logs' , class: 'btn btn-danger'%><br>
<br>

</div>

<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3"></div>

</div>

</div>

presencia/app/views/usuarios/index.html.erb
<div class="text-center">
  
  <p id="notice"><%= notice %></p>

  <h2 style="margin-bottom: 30px;"><b>Gestión de Empleados</b></h2>
  <div class="table-responsive" style="margin-left: 15px; margin-right: 15px;">
    <table class="table table-condensed table-hover">
      <thead>
        <tr>
          <th class="encabezado success">Código</th>
          <th class="encabezado info">Nombre</th>
          <th class="encabezado encabezado success">Apellidos</th>
          <th class="encabezado info">Domicilio</th>
          <th class="encabezado success">Email</th>
          <th class="encabezado info">Centro</th>
          <th class="encabezado success">Tarjeta</th>
          <th class="encabezado info">Dentro</th>
          <th class="encabezado success">Activo</th>
          <th colspan="1"></th>
        </tr>
      </thead>

      <tbody>
        <% @usuarios.each do |usuario| %>
          <tr>
            <td class="cuerpo"><%= usuario.codigo %></td>
            <td class="cuerpo"><%= usuario.nombre %></td>
            <td class="cuerpo"><%= usuario.apellidos %></td>
            <td class="cuerpo"><%= usuario.domicilio %></td>
            <td class="cuerpo"><%= usuario.email %></td>
            <td class="cuerpo"><%= usuario.centro %></td>
            <td class="cuerpo"><%=
               if !usuario.card.nil?
                 usuario.card.codigo
               end
             %></td>            
            <td class="cuerpo">
              <% if usuario.dentro == 1 %>
              <%= r = "SÍ" %>
              <% else %>
              <%= r = "NO" %>
              <% end %>
            </td>
            <td class="cuerpo">
            <% if usuario.activo == 1 %>
              <%= r = "SÍ" %>
              <% else %>
              <%= r = "NO" %>
              <% end %>
            </td>
            <td style="border-bottom: 1px solid #CCCCCC;">
              <%= link_to 'Ver', usuario , class: "btn btn-default btn-sm" %>
              <%= link_to 'Editar', edit_usuario_path(usuario), class: "btn btn-primary btn-sm" %>
              <%= link_to 'Borrar', usuario, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
            </td>
          </tr>
        <% end %>
      </tbody>
</table>
  </div>
  <br>

  <%= link_to 'Nuevo Empleado', new_usuario_path , {class: "btn btn-default"} %>
  <%= link_to 'Volver', {controller: "main", action: "gestion"}, {class: "btn btn-danger"} %>


</div>

presencia/app/views/usuarios/show.html.erb
<div class="text-center">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Codigo:</strong>
    <%= @usuario.codigo %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= @usuario.nombre %>
  </p>

  <p>
    <strong>Apellidos:</strong>
    <%= @usuario.apellidos %>
  </p>

  <p>
    <strong>Dni:</strong>
    <%= @usuario.dni %>
  </p>

  <p>
    <strong>Domicilio:</strong>
    <%= @usuario.domicilio %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @usuario.email %>
  </p>

  <p>
    <strong>Centro:</strong>
    <%= @usuario.centro %>
  </p>

  <p>
    <strong>Tarjeta:</strong>
    <%= 
       if !@usuario.card.nil?
         @usuario.card.codigo
       end 
     %>
  </p>

  <p>
    <strong>Dentro:</strong>
    <% if @usuario.dentro == 1 %>
    <%= r = "SÍ" %>
    <% else %>
    <%= r = "NO" %>
    <% end %>
  </p>

  <p>
    <strong>Activo:</strong>
    <% if @usuario.activo == 1 %>
    <%= r = "SÍ" %>
    <% else %>
    <%= r = "NO" %>
    <% end %>
  </p>

  <%= link_to 'Editar', edit_usuario_path(@usuario) , class: 'btn btn-primary'%> 
  <%= link_to 'Volver', usuarios_path, class: 'btn btn-danger' %>
</div>