cliente/RFID-US/config/routes.rb
Rails.application.routes.draw do
  resources :a_serverconfigurations

  devise_for :users

  root 'a_serverconfigurations#index'

end

cliente/RFID-US/app/models/a_serverconfiguration.rb
class AServerconfiguration < ActiveRecord::Base
end

cliente/RFID-US/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

cliente/RFID-US/app/controllers/a_serverconfigurations_controller.rb
class AServerconfigurationsController < ApplicationController
  before_action :set_a_serverconfiguration, only: [:show, :edit, :update, :destroy]

  # GET /a_serverconfigurations
  # GET /a_serverconfigurations.json
  def index
    @a_serverconfigurations = AServerconfiguration.all
  end

  # GET /a_serverconfigurations/1
  # GET /a_serverconfigurations/1.json
  def show
  end

  # GET /a_serverconfigurations/new
  def new
    @a_serverconfiguration = AServerconfiguration.new
  end

  # GET /a_serverconfigurations/1/edit
  def edit
	
  end

  # POST /a_serverconfigurations
  # POST /a_serverconfigurations.json
  def create
    @a_serverconfiguration = AServerconfiguration.new(a_serverconfiguration_params)

    respond_to do |format|
      if @a_serverconfiguration.save
        format.html { redirect_to @a_serverconfiguration, notice: 'A serverconfiguration was successfully created.' }
        format.json { render :show, status: :created, location: @a_serverconfiguration }
      else
        format.html { render :new }
        format.json { render json: @a_serverconfiguration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /a_serverconfigurations/1
  # PATCH/PUT /a_serverconfigurations/1.json
  def update
    respond_to do |format|
      if @a_serverconfiguration.update(a_serverconfiguration_params)
        format.html { redirect_to @a_serverconfiguration, notice: 'Device configuration was successfully updated. Next time, you have to access to new ip configuration. Rebooting device, this would take a while...' }
       format.json { render :show, status: :ok, location: @a_serverconfiguration }
	Thread.new do      
 		exec "sudo python /home/pi/Desktop/starting.py"
	end
      else
        format.html { render :edit }
        format.json { render json: @a_serverconfiguration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /a_serverconfigurations/1
  # DELETE /a_serverconfigurations/1.json
  def destroy
    @a_serverconfiguration.destroy
    respond_to do |format|
      format.html { redirect_to a_serverconfigurations_url, notice: 'A serverconfiguration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_a_serverconfiguration
      @a_serverconfiguration = AServerconfiguration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def a_serverconfiguration_params
      params.require(:a_serverconfiguration).permit(:ipdevice, :networkmask, :gateway, :dns1, :url_server, :refreshtime, :refreshtime_error)
    end
end

cliente/RFID-US/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

cliente/RFID-US/app/controllers/login_controller.rb
before_action :authenticate_user!

class LoginController < ApplicationController
 def index
   render text: 'You have found my secret place!'
 end
end

cliente/RFID-US/app/helpers/a_serverconfigurations_helper.rb
module AServerconfigurationsHelper
end

cliente/RFID-US/app/helpers/application_helper.rb
module ApplicationHelper
end

cliente/RFID-US/app/helpers/login_helper.rb
module LoginHelper
end

cliente/RFID-US/app/views/a_serverconfigurations/_form.html.erb
<%= form_for(@a_serverconfiguration) do |f| %>
  <% if @a_serverconfiguration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@a_serverconfiguration.errors.count, "error") %> prohibited this a_serverconfiguration from being saved:</h2>

      <ul>
      <% @a_serverconfiguration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :IP_del_dispositivo %><br>
    <%= f.text_field :ipdevice %>
  </div>
  <div class="field">
    <%= f.label :Máscara_de_red %><br>
    <%= f.text_field :networkmask %>
  </div>
  <div class="field">
    <%= f.label :Puerta_de_enlace %><br>
    <%= f.text_field :gateway %>
  </div>
  <div class="field">
    <%= f.label :Dns %><br>
    <%= f.text_field :dns1 %>
  </div>
  <div class="field">
    <%= f.label :Dirección_URL_del_servidor %><br>
    <%= f.text_area :url_server %>
  </div>
  <div class="field">
    <%= f.label :Tasa_de_refresco %><br>
    <%= f.number_field :refreshtime %>
  </div>
    <div class="field">
    <%= f.label :Tasa_de_refresco_en_caso_de_error %><br>
    <%= f.number_field :refreshtime_error %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar cambios" %>
  </div>
<% end %>

cliente/RFID-US/app/views/a_serverconfigurations/edit.html.erb
<h1>Editar la configuración del dispositivo</h1>

<font color="red">El dispositivo se reiniciará tras aplicar los cambios.</font>

<%= render 'form' %>

<%= link_to 'Back', a_serverconfigurations_path %>

cliente/RFID-US/app/views/a_serverconfigurations/index.html.erb
<h1>Configuración de control de presencia Sinapse</h1>
<tbody>
<div class="Tabla1" >
<table border="1" style="width:300px">
<caption><b>Configuración de red</b></caption>
  
    <tr>
      <td><b>IP dispositivo</b></td>
      <td><b>Máscara de red</b></td>
      <td><b>Puerta de enlace</b></td>
	  <td><b>DNS</b></td>
         </tr>
  
    <% @a_serverconfigurations.each do |a_serverconfiguration| %>
      <tr>
        <td><%= a_serverconfiguration.ipdevice %></td>
        <td><%= a_serverconfiguration.networkmask %></td>
        <td><%= a_serverconfiguration.gateway %></td>
		<td><%= a_serverconfiguration.dns1 %></td>
       </tr>
    
</table>

<a>
</a>
<a>
</a>

<br>
</br>

<table border="1" style="width:300px">
<caption><b>Configuración del servidor</b></caption>
  
    <tr>
      <td><b>Dirección url del servidor</b></td>
      <td><b>Tiempo de refresco (min)</b></td>   
	  <td><b>Tiempo de refresco en caso de error (min)</b></td>   
    </tr>

      <tr>
        <td><%= a_serverconfiguration.url_server %></td>
        <td><%= a_serverconfiguration.refreshtime %></td>
		<td><%= a_serverconfiguration.refreshtime_error %></td>
        </tr>   
  
</table>

</div>
<br>

 <%= link_to 'Edit', edit_a_serverconfiguration_path(a_serverconfiguration) %>

<% end %>

cliente/RFID-US/app/views/a_serverconfigurations/new.html.erb
<h1>New a_serverconfiguration</h1>

<%= render 'form' %>

<%= link_to 'Back', a_serverconfigurations_path %>

cliente/RFID-US/app/views/a_serverconfigurations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>IP del dispositivo:</strong>
  <%= @a_serverconfiguration.ipdevice %>
</p>

<p>
  <strong>Máscara de red:</strong>
  <%= @a_serverconfiguration.networkmask %>
</p>

<p>
  <strong>Puerta de enlace:</strong>
  <%= @a_serverconfiguration.gateway %>
</p>

<p>
  <strong>DNS:</strong>
  <%= @a_serverconfiguration.dns1 %>
</p>


<p>
  <strong>Url del servidor:</strong>
  <%= @a_serverconfiguration.url_server %>
</p>

<p>
  <strong>Tiempo de refresco:</strong>
  <%= @a_serverconfiguration.refreshtime %>
</p>

<p>
  <strong>Tiempo de refresco en caso de error:</strong>
  <%= @a_serverconfiguration.refreshtime_error %>
</p>

cliente/RFID-US/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


<head>
   <%=image_tag("CABECERASINAPSE.png") %><p></p>
  <title>Configuración de control presencial Sinapse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>